import {
  Alpha,
  AlphaBg,
  AlphaLogo,
  School,
  SchoolBg,
  SchoolLogo,
  Soflet,
  SofletBg,
  SofletLogo,
  SweatCoinBg,
  SweatcoinLogo,
  SwetCoin,
} from "../assets";

export const PortfolioMock = [
  {
    headerimage: SweatcoinLogo,
    bgimage: SweatCoinBg,
    image: SwetCoin,
    para: "A new breed of step counter and activity tracker that converts your steps into a currency you can spend on gadgets, sports and fitness kit, services and experiences. You can exchange them with friends and family.",
    download: "50M+",
    rating: "4.6/5",
    funding: "$20M",
    reward: "Rewards | Wallet | Tracker | eCommerce | Fintech",
  },
  {
    headerimage: AlphaLogo,
    bgimage: AlphaBg,
    image: Alpha,
    para: "Alpha pro- the seamless, easy-to-use mobile application for individual service providers, freelancers and gig workers. Turn any skill you have into your own small business and boost your income.",
    download: "50M+",
    rating: "50+",
    funding: "10K+",
    reward: "Instant Chat | Wallet | Fintech | Api",
  },
  {
    headerimage: SchoolLogo,
    bgimage: SchoolBg,
    image: School,
    para: "A National, full-service provider of health supplies and services to health professionals in educational settings from pre-school to college. SH Connect simplifies AED readiness  with its user-friendly interface.",
    download: "50M+",
    rating: "4.6/5",
    funding: "$20M",
    reward: "Inspection | Health | Training | Status | Compliance",
  },
  {
    headerimage: SofletLogo,
    bgimage: SofletBg,
    image: Soflet,
    para: "SOFLETE is the premier strength and conditioning work for the combat athlete,combined with innovative daily dry fire drills as well as weekly live fire drills at your finger tips.There is nothing like SOFLETE on the planet.",
    download: "10K+",
    rating: "4.6/5",
    funding: "$20M",
    reward: "|Athlete App | Muscle Mania | Fitness Tracker | Fintech |",
  },
];
